### ISSUE TITLE
swipeleft and swiperight are invalid

### ISSUE THREAD

**Issue by NathanielDavid** [bsdfzzzy/vue2-hammer#1]
`[vue-hammer] invalid event type: swipeleft`

**Comment by DrewLinzmaierGarratt** [comment]
Same here I'm afraid. Got around the issue by detecting direction.

**Comment by bsdfzzzy** [comment]
@NathanielDavid 
@DrewLinzmaierGarratt 
Sorry for late.I have fixed that. And I update the readme. You can find the gestures and directions supported now and you can use something like `v-hammer:swipe.left`.

**Comment by bsdfzzzy** [comment]
If this helps, I will close this issue.
