### ISSUE TITLE
how do i get attribute of the element or pass element attribute if this is not a handler function

### ISSUE THREAD

**Issue by lim-enhui** [bsdfzzzy/vue2-hammer#11]
how do i work with this??? i need to get the id but the tap doesnt pass args... this is generated in v-for example

`        circle(v-else
        :key='key'
        :r="getNodeSize(node) / 2"
        v-hammer:pan="onPan"
        v-hammer:tap="onTap"
        :id="node.id"
        :cx="node.x"
        :cy="node.y"
        :style='nodeStyle(node)'
        :title="node.name"
        :class="nodeClass(node)"
        :ref="'nodecircle ' + node.id"
        v-bind='node._svgAttrs'
        )`

**Comment by pajtai** [comment]
@lim-enhui you can follow:

```html
<div hammer:tap="() => onTap(node.id)">
```

see: https://github.com/vuejs/vue/issues/5588#issuecomment-299138559
