### ISSUE TITLE
IE 11 error: "Expected: ':'"

### ISSUE THREAD

**Issue by Demy** [bsdfzzzy/vue2-hammer#15]
I added the plugin to the site and it works fine in Chrome, but in IE it throws the error.
Expected: ':'
There's even no need to call something, the error appears immediately after "include" and "use" of the plugin.

**Comment by bsdfzzzy** [comment]
Can you show me the  whole log?

**Comment by Demy** [comment]
It's not very informative:
```
SCRIPT1003: Expected ':'
File: app.js, Line: 3126, Column: 1
```
And it points to the hammer plugin included to the app.js and minified. 
So, it's the full code of the plugin.

I think it might have something to do with IE inner code keys, like, it thinks that something in the plugin looks like an IE command. But it's just a guess.

**Comment by Demy** [comment]
Update: it points to 
```
t.directive("hammer",{
     bind(t,n) {
```
Exact place: `bind<the cursor points here>(t,n) {`

**Comment by controversial** [comment]
getting the same error. It's because this is es6 syntax for defining the function as an object property implicitly without manually setting a key.

**Comment by k0ph1e** [comment]
I'm also experiencing this issue. Is there known solution about this?

**Comment by bsdfzzzy** [comment]
Everyone, I have already publish a 2.0.0 version, if this issues still exist, please let me know.
