### ISSUE TITLE
index.min.js depends on babel-runtime

### ISSUE THREAD

**Issue by Findus23** [bsdfzzzy/vue2-hammer#18]
Hi,

After updating vue2-hammer to 2.0.0, my webpack build fails. This seems to be because the `index.min.js` includes the following part
```javascript
var _keys=require("babel-runtime/core-js/object/keys");
```
But as the dependency is never mentioned in the package.json webpack fails with the following error:

```text
This dependency was not found:

* babel-runtime/core-js/object/keys in ./node_modules/vue2-hammer/index.min.js
```

**Comment by bsdfzzzy** [comment]
Thanks, I fixed that at version 2.0.1.
