### ISSUE TITLE
invalid event type: panstart & pandend

### ISSUE THREAD

**Issue by sebmor** [bsdfzzzy/vue2-hammer#19]
I'm getting a warning in chrome console when I use panstart and panend events. 

![screen shot 2018-08-18 at 18 49 13](https://user-images.githubusercontent.com/405407/44301457-7b1eee00-a317-11e8-82d7-558dde86c856.png)

```
<div
  v-hammer:panstart="slideStart"
  v-hammer:pan.horizontal="slideMove"
  v-hammer:panend="slideEnd"
></div>
```

**Comment by sebmor** [comment]
After reading closed issues, it is my understanding that these are not supported? Why not? I would expect a 1 to 1 copy of HammerJS?

**Comment by bsdfzzzy** [comment]
You're right. You can listen to the start and end event inside the pan organizer.
