### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by etiennea** [bsdfzzzy/vue2-hammer#3]
For some reason I cannot build my project with this included. Any ideas why?

```
ERROR in app/js/vendor.8af7bc92f1da0f64bc78.js from UglifyJs
Unexpected token: punc (() [./node_modules/vue2-hammer/index.js:13,0][assests/app/js/vendor.8af7bc92f1da0f64bc78.js:38480,10]
```

**Comment by bsdfzzzy** [comment]
@etiennea  UglifyJs does not fully support es6. So you can first use babel to compile your project and then uglify it.

**Comment by etiennea** [comment]
Thanks!
